name: Feature flag check

on:
  workflow_call:
    inputs:
      runs-on:
        description: Runner label
        type: string
        default: ubuntu-latest

jobs:
  check:
    name: check
    runs-on: ${{ inputs.runs-on }}
    container:
      image: python:3.12-bookworm
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Validate feature flags
        uses: agiletec-inc/github-actions/.github/actions/feature-flag@faf4cdde6e57c970df29bb912fb57406ca33d0ad
        with:
          repository-path: .
